// lib/models/candidate_model.dart (CORRECTED)

class Candidate {
  final String id;
  final String fullname;
  final String position;
  final String manifesto;
  final String party;
  final String department;
  final String course;
  final String yearLevel;
  final String srCode;
  final String imageUrl;

  const Candidate({
    required this.id,
    required this.fullname,
    required this.position,
    required this.manifesto,
    required this.party,
    required this.department,
    required this.course,
    required this.yearLevel,
    required this.srCode,
    required this.imageUrl,
  });

  factory Candidate.fromJson(Map<String, dynamic> json) {
    return Candidate(
      id: json['id'] as String,
      fullname: json['fullname'] as String,
      position: json['position'] as String,
      manifesto: json['manifesto'] as String,
      party: json['party'] as String,
      department: json['department'] as String,
      course: json['course'] as String,
      yearLevel: json['yearLevel'] as String,
      srCode: json['srCode'] as String,
      imageUrl: json['imageUrl'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'fullname': fullname,
      'position': position,
      'manifesto': manifesto,
      'party': party,
      'department': department,
      'course': course,
      'yearLevel': yearLevel,
      'srCode': srCode,
      'imageUrl': imageUrl,
    };
  }

  // Optional: For easier debugging/printing
  @override
  String toString() {
    return 'Candidate(id: $id, name: $fullname, position: $position, manifesto: $manifesto: party: $party, imageUrl: $imageUrl)';
  }

  // Optional: For equality comparison in lists or sets
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Candidate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          fullname == other.fullname &&
          position == other.position &&
          party == other.party &&
          imageUrl == other.imageUrl;

  @override
  int get hashCode =>
      id.hashCode ^
      fullname.hashCode ^
      position.hashCode ^
      party.hashCode ^
      imageUrl.hashCode;
}

const List<Candidate> candidates = [
  Candidate(
    id: 'P001',
    fullname: 'Harvy A. Winceslao',
    position: 'President',
    manifesto: 'Building a stronger community through active participation.',
    party: 'Student\'s Voice Party',
    department: 'CICS',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00001',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P002',
    fullname: 'Sophia L. Ramirez',
    position: 'President',
    manifesto: 'Leading with integrity for student welfare.',
    party: 'Youth Empowerment Alliance',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00002',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P026',
    fullname: 'David H. Castro',
    position: 'President',
    manifesto: 'Uniting students for a common goal.',
    party: 'Independent',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00003',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // VP for External
  Candidate(
    id: 'P005',
    fullname: 'Noah R. Garcia',
    position: 'VP for External',
    manifesto: 'Connecting students with external opportunities.',
    party: 'Student\'s Voice Party',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00004',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P006',
    fullname: 'Emma C. Reyes',
    position: 'VP for External',
    manifesto: 'Expanding partnerships for student growth.',
    party: 'Youth Empowerment Alliance',
    department: 'CICS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00005',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P028',
    fullname: 'Henry J. Flores',
    position: 'VP for External',
    manifesto: 'Creating new avenues for student engagement.',
    party: 'Independent',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00006',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // Deputy Secretary
  Candidate(
    id: 'P007',
    fullname: 'Ava P. Cruz',
    position: 'Deputy Secretary',
    manifesto: 'Ensuring clear communication and records.',
    party: 'Student\'s Voice Party',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00007',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P008',
    fullname: 'Elijah D. Mendoza',
    position: 'Deputy Secretary',
    manifesto: 'Organizing information for efficiency.',
    party: 'Youth Empowerment Alliance',
    department: 'CTE',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00008',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P029',
    fullname: 'Chloe K. Gonzales',
    position: 'Deputy Secretary',
    manifesto: 'Efficient record-keeping for all.',
    party: 'Student\'s Voice Party',
    department: 'CICS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00009',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P042',
    fullname: 'Mila X. Rivera',
    position: 'Deputy Secretary',
    manifesto: 'Organized and efficient administration.',
    party: 'Independent',
    department: 'CABEIHM',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00010',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // Deputy Finance Officer
  Candidate(
    id: 'P009',
    fullname: 'Isabella F. Torres',
    position: 'Deputy Finance Officer',
    manifesto: 'Managing funds responsibly for student projects.',
    party: 'Student\'s Voice Party',
    department: 'CABEIHM',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00011',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P010',
    fullname: 'Lucas G. Aquino',
    position: 'Deputy Finance Officer',
    manifesto: 'Transparent financial management.',
    party: 'Youth Empowerment Alliance',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00012',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P030',
    fullname: 'Jackson L. Lim',
    position: 'Deputy Finance Officer',
    manifesto: 'Prudent financial planning for student initiatives.',
    party: 'Youth Empowerment Alliance',
    department: 'CTE',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00013',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P043',
    fullname: 'Owen Y. Flores',
    position: 'Deputy Finance Officer',
    manifesto: 'Ensuring responsible use of student funds.',
    party: 'Independent',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00014',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // Auditor
  Candidate(
    id: 'P011',
    fullname: 'Mia H. Castro',
    position: 'Auditor',
    manifesto: 'Ensuring accountability and transparency.',
    party: 'Student\'s Voice Party',
    department: 'CICS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00015',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P012',
    fullname: 'Alexander J. Rivera',
    position: 'Auditor',
    manifesto: 'Upholding financial integrity.',
    party: 'Youth Empowerment Alliance',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00016',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P031',
    fullname: 'Lily M. Tan',
    position: 'Auditor',
    manifesto: 'Ensuring fiscal responsibility.',
    party: 'Student\'s Voice Party',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00017',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P044',
    fullname: 'Nora Z. Gonzales',
    position: 'Auditor',
    manifesto: 'Promoting financial transparency.',
    party: 'Independent',
    department: 'CICS',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00018',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // Media Specialist
  Candidate(
    id: 'P013',
    fullname: 'Charlotte B. Flores',
    position: 'Media Specialist',
    manifesto: 'Highlighting student achievements through media.',
    party: 'Student\'s Voice Party',
    department: 'CTE',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00019',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P014',
    fullname: 'James V. Gonzales',
    position: 'Media Specialist',
    manifesto: 'Innovating student communication channels.',
    party: 'Youth Empowerment Alliance',
    department: 'CABEIHM',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00020',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P032',
    fullname: 'Sebastian N. Dela Rosa',
    position: 'Media Specialist',
    manifesto: 'Amplifying student voices.',
    party: 'Youth Empowerment Alliance',
    department: 'CABEIHM',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00021',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P045',
    fullname: 'Caleb A. Lim',
    position: 'Media Specialist',
    manifesto: 'Capturing and sharing student stories.',
    party: 'Independent',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00022',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // Business Manager
  Candidate(
    id: 'P015',
    fullname: 'Amelia W. Lim',
    position: 'Business Manager',
    manifesto: 'Optimizing resources for student activities.',
    party: 'Student\'s Voice Party',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00023',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P016',
    fullname: 'Benjamin X. Tan',
    position: 'Business Manager',
    manifesto: 'Driving sustainable projects.',
    party: 'Youth Empowerment Alliance',
    department: 'CICS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00024',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P033',
    fullname: 'Zoey O. Bautista',
    position: 'Business Manager',
    manifesto: 'Resourceful and innovative project management.',
    party: 'Student\'s Voice Party',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00025',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // Public Information Officer
  Candidate(
    id: 'P017',
    fullname: 'Harper Y. Dela Rosa',
    position: 'Public Information Officer',
    manifesto: 'Keeping students informed and engaged.',
    party: 'Student\'s Voice Party',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00026',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P018',
    fullname: 'Daniel Z. Bautista',
    position: 'Public Information Officer',
    manifesto: 'Promoting student initiatives.',
    party: 'Youth Empowerment Alliance',
    department: 'CTE',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00027',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P034',
    fullname: 'Gabriel P. Cruz',
    position: 'Public Information Officer',
    manifesto: 'Bridging communication gaps.',
    party: 'Youth Empowerment Alliance',
    department: 'CICS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00028',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // CTE Governor
  Candidate(
    id: 'P019',
    fullname: 'Evelyn A. Cruz',
    position: 'CTE Governor',
    manifesto: 'Representing CTE student interests.',
    party: 'Student\'s Voice Party',
    department: 'CTE',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00029',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P035',
    fullname: 'Victoria Q. Santos',
    position: 'CTE Governor',
    manifesto: 'Championing CTE student welfare.',
    party: 'Youth Empowerment Alliance',
    department: 'CTE',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00030',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // CAS Governor
  Candidate(
    id: 'P020',
    fullname: 'Matthew B. Santos',
    position: 'CAS Governor',
    manifesto: 'Advocating for CAS student needs.',
    party: 'Youth Empowerment Alliance',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00031',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P036',
    fullname: 'Carter R. Garcia',
    position: 'CAS Governor',
    manifesto: 'Fostering a vibrant CAS community.',
    party: 'Student\'s Voice Party',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00032',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // CET Governor
  Candidate(
    id: 'P021',
    fullname: 'Abigail C. Garcia',
    position: 'CET Governor',
    manifesto: 'Empowering CET students.',
    party: 'Student\'s Voice Party',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00033',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P037',
    fullname: 'Scarlett S. Reyes',
    position: 'CET Governor',
    manifesto: 'Driving progress for CET students.',
    party: 'Youth Empowerment Alliance',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00034',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // CABEIHM Governor
  Candidate(
    id: 'P022',
    fullname: 'Joseph D. Reyes',
    position: 'CABEIHM Governor',
    manifesto: 'Supporting CABEIHM student success.',
    party: 'Youth Empowerment Alliance',
    department: 'CABEIHM',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00035',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P038',
    fullname: 'Julian T. Mendoza',
    position: 'CABEIHM Governor',
    manifesto: 'Empowering future leaders in CABEIHM.',
    party: 'Student\'s Voice Party',
    department: 'CABEIHM',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00036',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // CICS Governor
  Candidate(
    id: 'P023',
    fullname: 'Elizabeth E. Mendoza',
    position: 'CICS Governor',
    manifesto: 'Innovating for CICS students.',
    party: 'Student\'s Voice Party',
    department: 'CICS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00037',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P039',
    fullname: 'Penelope U. Torres',
    position: 'CICS Governor',
    manifesto: 'Advancing CICS student opportunities.',
    party: 'Youth Empowerment Alliance',
    department: 'CICS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00038',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // Safety Officer
  Candidate(
    id: 'P024',
    fullname: 'Samuel F. Torres',
    position: 'Safety Officer',
    manifesto: 'Ensuring a safe campus environment.',
    party: 'Youth Empowerment Alliance',
    department: 'CTE',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00039',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P040',
    fullname: 'Leo V. Aquino',
    position: 'Safety Officer',
    manifesto: 'Prioritizing student safety.',
    party: 'Student\'s Voice Party',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00040',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // Technical Operation
  Candidate(
    id: 'P025',
    fullname: 'Sofia G. Aquino',
    position: 'Technical Operation',
    manifesto: 'Streamlining technical support for events.',
    party: 'Student\'s Voice Party',
    department: 'CICS',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00041',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P041',
    fullname: 'Luna W. Castro',
    position: 'Technical Operation',
    manifesto: 'Seamless technical support for all.',
    party: 'Youth Empowerment Alliance',
    department: 'CTE',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00042',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  // Income Generation and Sponsorship
  Candidate(
    id: 'P046',
    fullname: 'Ethan Q. Dela Cruz',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Securing resources for student initiatives.',
    party: 'Student\'s Voice Party',
    department: 'CABEIHM',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00043',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P047',
    fullname: 'Aria R. Santos',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Innovative fundraising for student projects.',
    party: 'Youth Empowerment Alliance',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '22-00044',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P048',
    fullname: 'Mason S. Garcia',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Building strong partnerships for sponsorships.',
    party: 'Independent',
    department: 'CICS',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00045',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P049',
    fullname: 'Ella T. Reyes',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Maximizing income for student welfare.',
    party: 'Student\'s Voice Party',
    department: 'CTE',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00046',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
  Candidate(
    id: 'P050',
    fullname: 'Logan U. Mendoza',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Sustainable funding for campus activities.',
    party: 'Youth Empowerment Alliance',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00047',
    imageUrl: 'assets/images/candidate_placeholder.png',
  ),
];
