// lib/models/candidate_model.dart (CORRECTED)

class Candidate {
  final String id;
  final String fullname;
  final String position;
  final String manifesto;
  final String party;
  final String department;
  final String course;
  final String yearLevel;
  final String srCode;
  final String imageUrl;

  const Candidate({
    required this.id,
    required this.fullname,
    required this.position,
    required this.manifesto,
    required this.party,
    required this.department,
    required this.course,
    required this.yearLevel,
    required this.srCode,
    required this.imageUrl,
  });

  factory Candidate.fromJson(Map<String, dynamic> json) {
    return Candidate(
      id: json['id'] as String,
      fullname: json['fullname'] as String,
      position: json['position'] as String,
      manifesto: json['manifesto'] as String,
      party: json['party'] as String,
      department: json['department'] as String,
      course: json['course'] as String,
      yearLevel: json['yearLevel'] as String,
      srCode: json['srCode'] as String,
      imageUrl: json['imageUrl'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'fullname': fullname,
      'position': position,
      'manifesto': manifesto,
      'party': party,
      'department': department,
      'course': course,
      'yearLevel': yearLevel,
      'srCode': srCode,
      'imageUrl': imageUrl,
    };
  }

  // Optional: For easier debugging/printing
  @override
  String toString() {
    return 'Candidate(id: $id, name: $fullname, position: $position, manifesto: $manifesto: party: $party, imageUrl: $imageUrl)';
  }

  // Optional: For equality comparison in lists or sets
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Candidate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          fullname == other.fullname &&
          position == other.position &&
          party == other.party &&
          imageUrl == other.imageUrl;

  @override
  int get hashCode =>
      id.hashCode ^
      fullname.hashCode ^
      position.hashCode ^
      party.hashCode ^
      imageUrl.hashCode;
}

const List<Candidate> candidates = [
  Candidate(
    id: 'P001',
    fullname: 'Harvy A. Winceslao',
    position: 'President',
    manifesto:
        'To bridge the gap between academic life and professional success, equipping you with the skills, connections, and opportunities to thrive in your chosen career path.',
    party: 'UNI-TEAM Advocates',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '4',
    srCode: '22-41234',
    imageUrl: 'assets/images/candidates/Harvy.jpg',
  ),
  Candidate(
    id: 'P002',
    fullname: 'Francis Andrei M. Anciado',
    position: 'President',
    manifesto:
        'To transform our learning environment into a dynamic hub of knowledge and groundbreaking ideas, ensuring every student has the tools to excel and innovate.',
    party: 'STUDENT PowerHouse',
    department: 'CTE',
    course: 'BS Physical Education',
    yearLevel: '4',
    srCode: '22-80026',
    imageUrl: 'assets/images/candidates/Francis.jpg',
  ),
  Candidate(
    id: 'P003',
    fullname: 'Madizon Mae E. Dela Vega',
    position: 'President',
    manifesto:
        'To prioritize your mental, physical, and financial well-being, creating a supportive campus community where every student feels safe, valued, and ready to thrive.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CET',
    course: 'Bachelor of Food Engineering Technology',
    yearLevel: '4',
    srCode: '22-24211',
    imageUrl: 'assets/images/candidates/Madizon.jpg',
  ),

  // VP for Internal
  Candidate(
    id: 'P004',
    fullname: 'Aldrey C. Machonaga',
    position: 'VP for Internal',
    manifesto: 'Free Wi-Fi: Fast, reliable, everywhere.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CET',
    course: 'Bachelor of Computer Engineering Technology',
    yearLevel: '4',
    srCode: '22-69008',
    imageUrl: 'assets/images/candidates/Aldrey.jpg',
  ),
  Candidate(
    id: 'P005',
    fullname: 'Ashley Mae R. Gonzalez',
    position: 'VP for Internal',
    manifesto: 'Leading with integrity for student welfare.',
    party: 'STUDENT PowerHouse',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '4',
    srCode: '22-28425',
    imageUrl: 'assets/images/candidates/Ashley.jpg',
  ),
  Candidate(
    id: 'P006',
    fullname: 'Vherra G. Monteflanco',
    position: 'VP for Internal',
    manifesto: '"Skill Up!" workshops for every college.',
    party: 'UNI-TEAM Advocates',
    department: 'CABEIHM',
    course: 'BS Accounting',
    yearLevel: '4',
    srCode: '22-00143',
    imageUrl: 'assets/images/candidates/Vherra.jpg',
  ),
  Candidate(
    id: 'P007',
    fullname: 'James Aljandro Trinidad',
    position: 'VP for Internal',
    manifesto: 'Scholarship simplified: Easier access for everyone.',
    party: 'Independent',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '4',
    srCode: '22-48123',
    imageUrl: 'assets/images/candidates/BossJame.jpg',
  ),
  // VP for External
  Candidate(
    id: 'P008',
    fullname: 'Jericho Lester R. Garcia',
    position: 'VP for External',
    manifesto: 'Connecting students with external opportunities.',
    party: 'Independent',
    department: 'CET',
    course: 'BS Computer Science',
    yearLevel: '4',
    srCode: '22-00005',
    imageUrl: 'assets/images/candidates/Jericho.jpg',
  ),
  Candidate(
    id: 'P009',
    fullname: 'Patrick Vincent M. Lasala',
    position: 'VP for External',
    manifesto: 'Better sports facilities for all athletes.',
    party: 'STUDENT PowerHouse',
    department: 'CAS',
    course: 'BS Criminology',
    yearLevel: '3',
    srCode: '23-60429',
    imageUrl: 'assets/images/candidates/Patrick.jpg',
  ),
  Candidate(
    id: 'P010',
    fullname: 'Ariessa Mae C. Centeno ',
    position: 'VP for External',
    manifesto: 'Creating new avenues for student engagement.',
    party: 'UNI-TEAM Advocates',
    department: 'CABEIHM',
    course: 'BS Business Administration',
    yearLevel: '4',
    srCode: '22-72126',
    imageUrl: 'assets/images/candidates/Ariessa.jpg',
  ),
  Candidate(
    id: 'P011',
    fullname: 'Margarette De Grano ',
    position: 'VP for External',
    manifesto: 'Creating new avenues for student engagement.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CET',
    course: 'Bachelor of Food Engineering Technology',
    yearLevel: '4',
    srCode: '22-53728',
    imageUrl: 'assets/images/candidates/Margie.jpg',
  ),
  // Deputy Secretary
  Candidate(
    id: 'P012',
    fullname: 'Jenny Castillo D. Cero ',
    position: 'Deputy Secretary',
    manifesto: 'Ensuring clear communication and records.',
    party: 'Independent',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '2',
    srCode: '24-02341',
    imageUrl: 'assets/images/candidates/Jenny.jpg',
  ),
  Candidate(
    id: 'P013',
    fullname: 'Alyssa Mendoza ',
    position: 'Deputy Secretary',
    manifesto: 'Organizing information for efficiency.',
    party: 'UNI-TEAM Advocates',
    department: 'CABEIHM',
    course: 'BS Public Administration',
    yearLevel: '2',
    srCode: '24-02129',
    imageUrl: 'assets/images/candidates/Mendoza.jpg',
  ),
  Candidate(
    id: 'P014',
    fullname: 'Chloe K. Gonzales',
    position: 'Deputy Secretary',
    manifesto: 'Efficient record-keeping for all.',
    party: 'STUDENT PowerHouse',
    department: 'CTE',
    course: 'BS Secondary Education',
    yearLevel: '3',
    srCode: '23-00129',
    imageUrl: 'assets/images/candidates/Chloe.jpg',
  ),
  Candidate(
    id: 'P015',
    fullname: 'Kurt A. Labandelo',
    position: 'Deputy Secretary',
    manifesto: 'Organized and efficient administration.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CET',
    course: 'Bachelor of Automotive Engineering Technology',
    yearLevel: '4',
    srCode: '22-60049',
    imageUrl: 'assets/images/candidates/Kurt.jpg',
  ),
  // Deputy Finance Officer
  Candidate(
    id: 'P016',
    fullname: 'Niniela G. Orolfo',
    position: 'Deputy Finance Officer',
    manifesto: 'Managing funds responsibly for student projects.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CET',
    course: 'Bachelor of Computer Engineering Technology',
    yearLevel: '4',
    srCode: '22-09567',
    imageUrl: 'assets/images/candidates/Niniela.jpg',
  ),
  Candidate(
    id: 'P017',
    fullname: 'Lucas G. Aquino',
    position: 'Deputy Finance Officer',
    manifesto: 'Transparent financial management.',
    party: 'Independent',
    department: 'CABEIHM',
    course: 'BS Accounting',
    yearLevel: '2',
    srCode: '24-12867',
    imageUrl: 'assets/images/candidates/Lucas.jpg',
  ),
  Candidate(
    id: 'P018',
    fullname: 'Shaina San Buenaventura ',
    position: 'Deputy Finance Officer',
    manifesto: 'Prudent financial planning for student initiatives.',
    party: 'STUDENT PowerHouse',
    department: 'CTE',
    course: 'BS Elementary Education',
    yearLevel: '4',
    srCode: '22-18675',
    imageUrl: 'assets/images/candidates/Shaina.jpg',
  ),
  Candidate(
    id: 'P019',
    fullname: 'Rachel Mae Llarena',
    position: 'Deputy Finance Officer',
    manifesto: 'Ensuring responsible use of student funds.',
    party: 'UNI-TEAM Advocates',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '4',
    srCode: '22-56567',
    imageUrl: 'assets/images/candidates/Rachel.jpg',
  ),
  // Auditor
  Candidate(
    id: 'P020',
    fullname: 'Kenneth T. Onan',
    position: 'Auditor',
    manifesto: 'Ensuring accountability and transparency.',
    party: 'UNI-TEAM Advocates',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '4',
    srCode: '22-16727',
    imageUrl: 'assets/images/candidates/Kenneth.jpg',
  ),
  Candidate(
    id: 'P021',
    fullname: 'Jhona Marie C. Pineda',
    position: 'Auditor',
    manifesto: 'Upholding financial integrity.',
    party: 'STUDENT PowerHouse',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '23-10178',
    imageUrl: 'assets/images/candidates/Jhona.jpg',
  ),
  Candidate(
    id: 'P022',
    fullname: 'Andrew M. De Vera',
    position: 'Auditor',
    manifesto: 'Ensuring fiscal responsibility.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '3',
    srCode: '23-91828',
    imageUrl: 'assets/images/candidates/Andrew.jpg',
  ),
  Candidate(
    id: 'P023',
    fullname: 'Nora Z. Gonzales',
    position: 'Auditor',
    manifesto: 'Promoting financial transparency.',
    party: 'Independent',
    department: 'CABEIHM',
    course: 'BS Accounting',
    yearLevel: '2',
    srCode: '24-12867',
    imageUrl: 'assets/images/candidates/Nora.jpg',
  ),
  // Media Specialist
  Candidate(
    id: 'P024',
    fullname: 'Charlotte B. Flores',
    position: 'Media Specialist',
    manifesto: 'Highlighting student achievements through media.',
    party: 'Independent',
    department: 'CET',
    course: 'Bachelor of Drafting Engineering Technology',
    yearLevel: '2',
    srCode: '24-50051',
    imageUrl: 'assets/images/candidates/Charlotte.jpg',
  ),
  Candidate(
    id: 'P025',
    fullname: 'Paulynous V. Gonzales',
    position: 'Media Specialist',
    manifesto: 'Innovating student communication channels.',
    party: 'UNI-TEAM Advocates',
    department: 'CET',
    course: 'Bachelor of Drafting Engineering Technology',
    yearLevel: '4',
    srCode: '22-45456',
    imageUrl: 'assets/images/candidates/Paul.jpg',
  ),
  Candidate(
    id: 'P026',
    fullname: 'Kisha Marie C. Dela Rosa',
    position: 'Media Specialist',
    manifesto: 'Artist & performance spaces for creatives.',
    party: 'STUDENT PowerHouse',
    department: 'CAS',
    course: 'BS psychology',
    yearLevel: '3',
    srCode: '23-81818',
    imageUrl: 'assets/images/candidates/Kisha.jpg',
  ),
  Candidate(
    id: 'P027',
    fullname: 'Mark Oliver G. Mercado ',
    position: 'Media Specialist',
    manifesto: 'Capturing and sharing student stories.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CET',
    course: 'BS Drafting Engineering Technology',
    yearLevel: '3',
    srCode: '23-56789',
    imageUrl: 'assets/images/candidates/Mark.jpg',
  ),
  // Business Manager
  Candidate(
    id: 'P028',
    fullname: 'John Kerzy F. Arellano ',
    position: 'Business Manager',
    manifesto: 'Optimizing resources for student activities.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '4',
    srCode: '22-56789',
    imageUrl: 'assets/images/candidates/Kerzy.jpg',
  ),
  Candidate(
    id: 'P029',
    fullname: 'Christian Aeron M. Santos',
    position: 'Business Manager',
    manifesto: 'Driving sustainable projects.',
    party: 'UNI-TEAM Advocates',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '2',
    srCode: '24-94129',
    imageUrl: 'assets/images/candidates/Aeon.jpg',
  ),
  Candidate(
    id: 'P030',
    fullname: 'Zoey O. Bautista',
    position: 'Business Manager',
    manifesto: 'Resourceful and innovative project management.',
    party: 'STUDENT PowerHouse',
    department: 'CAS',
    course: 'BS Development Communication',
    yearLevel: '3',
    srCode: '23-10178',
    imageUrl: 'assets/images/candidates/Zoey.jpg',
  ),
  // Public Information Officer
  Candidate(
    id: 'P031',
    fullname: 'Harper Y. Dela Rosa',
    position: 'Public Information Officer',
    manifesto: 'Keeping students informed and engaged.',
    party: 'STUDENT PowerHouse',
    department: 'CAS',
    course: 'BS Development Communication',
    yearLevel: '3',
    srCode: '23-10189',
    imageUrl: 'assets/images/candidates/Harper.jpg',
  ),
  Candidate(
    id: 'P032',
    fullname: 'Daniel C. Catena',
    position: 'Public Information Officer',
    manifesto: 'Promoting student initiatives.',
    party: 'UNI-TEAM Advocates',
    department: 'CTE',
    course: 'BS Secondary Education',
    yearLevel: '4',
    srCode: '22-67671',
    imageUrl: 'assets/images/candidates/Catena.jpg',
  ),
  Candidate(
    id: 'P033',
    fullname: 'Jay A. Vanguarda',
    position: 'Public Information Officer',
    manifesto: 'Bridging communication gaps.',
    party: 'Youth Empowerment Alliance',
    department: 'CET',
    course: 'Bachelor of Computer Engineering Technology',
    yearLevel: '4',
    srCode: '22-67604',
    imageUrl: 'assets/images/candidates/Jay.jpg',
  ),
  // CTE Governor
  Candidate(
    id: 'P034',
    fullname: 'Evelyn A. Cruz',
    position: 'CTE Governor',
    manifesto: 'Representing CTE student interests.',
    party: 'STUDENT PowerHouse',
    department: 'CTE',
    course: 'BS Secondary Education',
    yearLevel: '3',
    srCode: '23-67888',
    imageUrl: 'assets/images/candidates/Evelyn.jpg',
  ),
  Candidate(
    id: 'P035',
    fullname: 'Victoria Q. Santos',
    position: 'CTE Governor',
    manifesto: 'Championing CTE student welfare.',
    party: 'UNI-TEAM Advocates',
    department: 'CTE',
    course: 'BS Physical Education',
    yearLevel: '4',
    srCode: '22-68872',
    imageUrl: 'assets/images/candidates/Victoria.jpg',
  ),
  // CAS Governor
  Candidate(
    id: 'P036',
    fullname: 'Dominic E. Malpica',
    position: 'CAS Governor',
    manifesto: 'Advocating for CAS student needs.',
    party: 'STUDENT PowerHouse',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '23-67189',
    imageUrl: 'assets/images/candidates/Dominic.jpg',
  ),
  Candidate(
    id: 'P037',
    fullname: 'Neil Ivan Tañamor ',
    position: 'CAS Governor',
    manifesto: 'Fostering a vibrant CAS community.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '23-99189',
    imageUrl: 'assets/images/candidates/Neil.jpg',
  ),
  // CET Governor
  Candidate(
    id: 'P038',
    fullname: 'Alyssa Mae C. Espiritu',
    position: 'CET Governor',
    manifesto: 'Empowering CET students.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CET',
    course: 'Bachelor of Drafting Engineering Technology',
    yearLevel: '4',
    srCode: '22-81818',
    imageUrl: 'assets/images/candidates/Aly.jpg',
  ),
  Candidate(
    id: 'P039',
    fullname: 'Scarlett S. Reyes',
    position: 'CET Governor',
    manifesto: 'Driving progress for CET students.',
    party: 'Independent',
    department: 'CET',
    course: 'Bachelor of Industrial Engineering Technology',
    yearLevel: '4',
    srCode: '22-67119',
    imageUrl: 'assets/images/candidates/Scarlet.jpg',
  ),
  // CABEIHM Governor
  Candidate(
    id: 'P040',
    fullname: 'Joseph D. Reyes',
    position: 'CABEIHM Governor',
    manifesto: 'Supporting CABEIHM student success.',
    party: 'STUDENT PowerHouse',
    department: 'CABEIHM',
    course: 'BS Tourism Management',
    yearLevel: '4',
    srCode: '22-66162',
    imageUrl: 'assets/images/candidates/Joseph.jpg',
  ),
  Candidate(
    id: 'P041',
    fullname: 'Julian T. Mendoza',
    position: 'CABEIHM Governor',
    manifesto: 'Empowering future leaders in CABEIHM.',
    party: 'UNI-TEAM Advocates',
    department: 'CABEIHM',
    course: 'BS Tourism Management',
    yearLevel: '4',
    srCode: '22-45152',
    imageUrl: 'assets/images/candidates/Julian.jpg',
  ),
  // CICS Governor
  Candidate(
    id: 'P042',
    fullname: 'Elizabeth E. Mendoza',
    position: 'CICS Governor',
    manifesto: 'Innovating for CICS students.',
    party: 'STUDENT PowerHouse',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '3',
    srCode: '23-10037',
    imageUrl: 'assets/images/candidates/Elizabeth.jpg',
  ),
  Candidate(
    id: 'P043',
    fullname: 'Carl Denver M. Diokno',
    position: 'CICS Governor',
    manifesto: 'Advancing CICS student opportunities.',
    party: 'Youth Empowerment Alliance',
    department: 'CICS',
    course: 'BS Information Technology',
    yearLevel: '3',
    srCode: '23-13038',
    imageUrl: 'assets/images/candidates/Denver.jpg',
  ),
  // Safety Officer
  Candidate(
    id: 'P044',
    fullname: 'Samuel F. Torres',
    position: 'Safety Officer',
    manifesto: 'Ensuring a safe campus environment.',
    party: 'UNI-TEAM Advocates',
    department: 'Independent',
    course: 'BS Elementary Education',
    yearLevel: '4',
    srCode: '22-67449',
    imageUrl: 'assets/images/candidates/Samuel.jpg',
  ),
  Candidate(
    id: 'P045',
    fullname: 'Leo V. Aquino',
    position: 'Safety Officer',
    manifesto: 'Prioritizing student safety.',
    party: 'STUDENT PowerHouse',
    department: 'CAS',
    course: 'BS Psychology',
    yearLevel: '3',
    srCode: '23-90100',
    imageUrl: 'assets/images/candidates/Leo.jpg',
  ),
  // Technical Operation
  Candidate(
    id: 'P046',
    fullname: 'Sofia G. Aquino',
    position: 'Technical Operation',
    manifesto: 'Streamlining technical support for events.',
    party: 'STUDENT PowerHouse',
    department: 'CTE',
    course: 'BS Physical Education',
    yearLevel: '4',
    srCode: '22-67689',
    imageUrl: 'assets/images/candidates/Sofia.jpg',
  ),
  Candidate(
    id: 'P047',
    fullname: 'Luna W. Castro',
    position: 'Technical Operation',
    manifesto: 'Seamless technical support for all.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CET',
    course: 'Bachelor of Computer Engineering Technology',
    yearLevel: '4',
    srCode: '22-67689',
    imageUrl: 'assets/images/candidates/Luna.jpg',
  ),
  // Income Generation and Sponsorship
  Candidate(
    id: 'P048',
    fullname: 'Ethan Q. Dela Cruz',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Securing resources for student initiatives.',
    party: 'UNI-TEAM Advocates',
    department: 'CABEIHM',
    course: 'BS Business Administration',
    yearLevel: '4',
    srCode: '22-67110',
    imageUrl: 'assets/images/candidates/Ethan.jpg',
  ),
  Candidate(
    id: 'P049',
    fullname: 'Aria R. Santos',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Innovative fundraising for student projects.',
    party: 'STUDENT PowerHouse',
    department: 'CABEIHM',
    course: 'BS Business Administration',
    yearLevel: '4',
    srCode: '22-44119',
    imageUrl: 'assets/images/candidates/Aria.jpg',
  ),
  Candidate(
    id: 'P050',
    fullname: 'Mason S. Garcia',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Building strong partnerships for sponsorships.',
    party: 'Independent',
    department: 'CABEIHM',
    course: 'BS Accounting',
    yearLevel: '4',
    srCode: '22-44009',
    imageUrl: 'assets/images/candidates/Mason.jpg',
  ),
  Candidate(
    id: 'P051',
    fullname: 'Edgar G. Carandang',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Maximizing income for student welfare.',
    party: 'S.A.L.P.A.K.E.R.S.',
    department: 'CET',
    course: 'BS Electrical Engineering Technology',
    yearLevel: '4',
    srCode: '22-82210',
    imageUrl: 'assets/images/candidates/Edgar.jpg',
  ),
  Candidate(
    id: 'P052',
    fullname: 'Sheena L. Licmo',
    position: 'Income Generation and Sponsorship',
    manifesto: 'Sustainable funding for campus activities.',
    party: 'Independent',
    department: 'CET',
    course: 'Bachelor of Electrical Engineering Technology',
    yearLevel: '4',
    srCode: '22-21515',
    imageUrl: 'assets/images/candidates/Sheena.jpg',
  ),
];
